# Example ProviderConfig with Basic Auth
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: default
type: Opaque
stringData:
  username: admin
  password: admin

---
apiVersion: gf.m.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: grafana-basic-auth
  namespace: default
spec:
  url: http://localhost:3000
  credentials:
    source: Secret
    authType: basic
    basicAuth:
      usernameSecretRef:
        namespace: default
        name: grafana-credentials
        key: username
      passwordSecretRef:
        namespace: default
        name: grafana-credentials
        key: password

# Example ProviderConfig with Service Token
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-token
  namespace: default
type: Opaque
stringData:
  token: glsa_xxxxxxxxxxxxxxxxxxxxx

---
apiVersion: gf.m.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: grafana-token-auth
  namespace: default
spec:
  url: http://localhost:3000
  credentials:
    source: Secret
    authType: token
    tokenAuth:
      tokenSecretRef:
        namespace: default
        name: grafana-token
        key: token
